// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldCupScores.Infrastructure.Persistence;

#nullable disable

namespace WorldCupScores.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603203000_AddWorldCupMatchColumnComments")]
    partial class AddWorldCupMatchColumnComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldCupScores.Domain.Entities.WorldCupMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique match identifier.");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer")
                        .HasComment("Optional away team score. Must be null while the match is scheduled.");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasComment("Name of the away team.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the match record was created.");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer")
                        .HasComment("Optional home team score. Must be null while the match is scheduled.");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasComment("Name of the home team.");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the match is scheduled to happen, stored with time zone.");

                    b.Property<string>("Stadium")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("Optional stadium or venue where the match is played.");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasComment("Competition stage. Values: 0=GroupStage, 1=RoundOf16, 2=QuarterFinal, 3=SemiFinal, 4=ThirdPlace, 5=Final.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Match lifecycle status. Values: 0=Scheduled, 1=InProgress, 2=Finished, 3=Canceled.");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp of the latest match record update, null when never updated.");

                    b.HasKey("Id");

                    b.ToTable("world_cup_matches", (string)null);

                    b.HasComment("World Cup match schedule, score and lifecycle data.");
                });
#pragma warning restore 612, 618
        }
    }
}
